apiVersion: v1
kind: Service
metadata:
  name: "demo-service-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 2000

  selector:
    app: "demo-service-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demo-service-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "demo-service-selector"
    spec:
      containers:
      - name: demo-service
        image: demo-service:latest
        readinessProbe:
          httpGet:
            path: /hello
            port: 2000
          initialDelaySeconds: 20
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
